"""Canonical JSON-Schema catalog for Sovyx log events.

Loaded at runtime via ``importlib.resources.files(__name__)``. The
schemas are generated by ``scripts/_gen_log_schemas.py`` — never
hand-edit them; edit the generator's table and re-run.

Use :func:`load` to fetch a single schema by event name, or
:func:`load_all` to enumerate the catalog.
"""

from __future__ import annotations

import json
from importlib.resources import files
from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from importlib.resources.abc import Traversable

__all__ = ["load", "load_all", "event_names"]


def _resources() -> Traversable:
    return files(__name__)


def event_names() -> list[str]:
    """Return every event name with a schema registered, sorted."""
    return sorted(
        path.name.removesuffix(".json")
        for path in _resources().iterdir()
        if path.name.endswith(".json")
    )


def load(event: str) -> dict[str, Any]:
    """Load the JSON-Schema for *event*. Raises ``FileNotFoundError`` if absent."""
    resource = _resources() / f"{event}.json"
    return json.loads(resource.read_text(encoding="utf-8"))


def load_all() -> dict[str, dict[str, Any]]:
    """Load every schema, keyed by event name."""
    return {name: load(name) for name in event_names()}
