"""voice — Voice activity detection, wake word, speech processing, and TTS pipeline."""

from __future__ import annotations

from sovyx.voice.audio import (
    AudioCapture,
    AudioCaptureConfig,
    AudioDucker,
    AudioOutput,
    AudioOutputConfig,
    AudioPlatform,
    OutputChunk,
    OutputPriority,
    RingBuffer,
    detect_platform,
    normalize_lufs,
)
from sovyx.voice.jarvis import (
    FILLER_BANK,
    FillerCategory,
    JarvisConfig,
    JarvisIllusion,
    split_at_boundaries,
    synthesize_beep,
    validate_jarvis_config,
)
from sovyx.voice.pipeline import (
    AudioOutputQueue,
    BargeInDetector,
    VoicePipeline,
    VoicePipelineConfig,
    VoicePipelineState,
)
from sovyx.voice.stt import (
    MoonshineConfig,
    MoonshineSTT,
    PartialTranscription,
    STTEngine,
    STTState,
    TranscriptionResult,
    TranscriptionSegment,
)
from sovyx.voice.stt_cloud import CloudSTT, CloudSTTConfig, CloudSTTError, needs_cloud_fallback
from sovyx.voice.tts_kokoro import KokoroConfig, KokoroTTS
from sovyx.voice.tts_piper import AudioChunk, PiperConfig, PiperTTS, TTSEngine
from sovyx.voice.vad import SileroVAD, VADConfig, VADEvent, VADState
from sovyx.voice.wake_word import (
    VerificationResult,
    WakeWordConfig,
    WakeWordDetector,
    WakeWordEvent,
    WakeWordState,
)
from sovyx.voice.wyoming import (
    SovyxWyomingServer,
    STTResult,
    TTSResult,
    WakeWordResult,
    WyomingClientHandler,
    WyomingConfig,
    WyomingEvent,
    build_service_info,
    get_local_ip,
    ndarray_to_pcm_bytes,
    pcm_bytes_to_ndarray,
    write_event,
)

__all__ = [
    "AudioCapture",
    "AudioCaptureConfig",
    "AudioChunk",
    "CloudSTT",
    "CloudSTTConfig",
    "CloudSTTError",
    "AudioDucker",
    "AudioOutput",
    "AudioOutputConfig",
    "AudioOutputQueue",
    "AudioPlatform",
    "BargeInDetector",
    "FILLER_BANK",
    "FillerCategory",
    "JarvisConfig",
    "JarvisIllusion",
    "KokoroConfig",
    "KokoroTTS",
    "OutputChunk",
    "OutputPriority",
    "RingBuffer",
    "detect_platform",
    "normalize_lufs",
    "MoonshineConfig",
    "MoonshineSTT",
    "PartialTranscription",
    "PiperConfig",
    "PiperTTS",
    "STTEngine",
    "STTState",
    "SileroVAD",
    "TTSEngine",
    "TranscriptionResult",
    "TranscriptionSegment",
    "VADConfig",
    "VADEvent",
    "VADState",
    "VerificationResult",
    "VoicePipeline",
    "VoicePipelineConfig",
    "VoicePipelineState",
    "WakeWordConfig",
    "WakeWordDetector",
    "WakeWordEvent",
    "WakeWordState",
    "split_at_boundaries",
    "synthesize_beep",
    "needs_cloud_fallback",
    "validate_jarvis_config",
    "STTResult",
    "SovyxWyomingServer",
    "TTSResult",
    "WakeWordResult",
    "WyomingClientHandler",
    "WyomingConfig",
    "WyomingEvent",
    "build_service_info",
    "get_local_ip",
    "ndarray_to_pcm_bytes",
    "pcm_bytes_to_ndarray",
    "write_event",
]
